version: '3.3'

services:
    db:
      image: mysql:latest
      container_name: mysql-db2
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=synergywaytest
      ports:
        - "3306:3306"
      restart: always
      volumes:
      - ./data:/docker-entrypoint-initdb.d


    airlanesservice:                        #it is just a name, which will be used only in this file.
      image: airlanes              #name of the image after dockerfile executes
      container_name: airlanes-service-app  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8080:8080"                       #docker containter port with your os port
      restart: always
        
      depends_on:                           #define dependencies of this app
        - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/synergywaytest?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root